### ISSUE TITLE
Video transcripts should be punctuated

### ISSUE THREAD

**Issue by JamesMcMinn** [FullFact/health-misinfo-shared#120]
### Overview
Currently transcripts are fairly difficult to read. We should look at adding punctuation to make it more readable.

David has suggested that we should look to use the existing [nlp-preprocesisng](https://github.com/FullFact/nlp-preprocessing/blob/main/nlp_preprocessing/restore_punctuation.py) code for this.

**Comment by ff-dh** [comment]
If we pass the transcripts through nlp-preprocessing (which requires a bigger server and adds more delay, it's slow) we'll have to do work to match up the unformatted output with the LLM-output or we'll lose the timestamps.

**Comment by dcorney** [comment]
Let's leave this for now. Once we have more user feedback we can decide if we need to do this in the final product, but I think the MVP is fine without this.
