### ISSUE TITLE
Consolidate json parsing into one implementation

### ISSUE THREAD

**Issue by dearden** [FullFact/health-misinfo-shared#122]
### Describe the bug

Currently we have two ways of doing json parsing, one in [vertex.py](https://github.com/FullFact/health-misinfo-shared/blob/be2f89cb04e1d41ee34facc318879547b9e5a0e2/src/health_misinfo_shared/vertex.py#L17) and one in [data_parsing.py](https://github.com/FullFact/health-misinfo-shared/blob/be2f89cb04e1d41ee34facc318879547b9e5a0e2/src/health_misinfo_shared/data_parsing.py#L17).

The latter one should be made to be used in production. They both do the same thing, but there's tests written for the second and it works in some edge cases.

**Comment by andylolz** [comment]
Looks like @c-j-johnston fixed this in 9c38a6ba30a91fa058fbec1dd86c84e854a4fd97.
