### ISSUE TITLE
Remove evaluation.py

### ISSUE THREAD

**Issue by dearden** [FullFact/health-misinfo-shared#131]
### Overview

We have a script in src called [evaluation.py](https://github.com/FullFact/health-misinfo-shared/blob/main/src/health_misinfo_shared/evaluation.py) which was what we were using for evaluation.

I believe it's functionality is now superseded by all the evaluation functionality in the [evaluation](https://github.com/FullFact/health-misinfo-shared/tree/main/evaluation) directory, specifically in [assert_evaluation_metrics.py](https://github.com/FullFact/health-misinfo-shared/blob/main/evaluation/assert_evaluation_metrics.py).

It's also possibly out of date, in terms of the input it expects and, as far as I'm aware, it is no longer in use. 

We should probably remove `src/evaluation.py`, to remove ambiguity between the two places. If there's a reason to keep the script, it should probably be moved to dev or something.

**Comment by dearden** [comment]
@dcorney Can you think of a reason not to remove this?

**Comment by dcorney** [comment]
No, you're right - it is very out of date. Please remove it.
