### ISSUE TITLE
Repeat claim extraction when LLM output is wrong

### ISSUE THREAD

**Issue by c-j-johnston** [FullFact/health-misinfo-shared#140]
### Overview

Sometimes, Gemini outputs are incorrect. They miss out a key in the JSON output (usually `original_text`) and this can cause the app to crash. However, this is rare, so allowing up to two retries in `llm.py` should prevent this from being a problem. On the third failure, only the failing claims should be returned.

### Requirements

1. An assertion function is created to ensure LLM output JSONs have the correct keys.
2. If the assertion fails for any output claim JSON, the LLM runs over the whole chunk again.
3. If the assertion fails a third time, we return a `null` on the offending value.
4. We test this.

**Comment by dearden** [comment]
On point 1:
I wrote some assertions for checking format over [in evaluation](https://github.com/FullFact/health-misinfo-shared/blob/main/evaluation/assert_check_format.py)

Although, if we had a dataclass with a `from_dict` function, it would be a lot easier to catch than it is with the dict

**Comment by andylolz** [comment]
Here is a similar sort of thing, but using pydantic (which we appear to have as a dependency anyway):

```python
from pydantic import BaseModel, ValidationError
from enum import Enum


class LabelEnum(Enum):
    understandability = "understandability"
    type_of_claim = "type_of_claim"
    type_of_medical_claim = "type_of_medical_claim"
    support = "support"
    harm = "harm"


class ClaimModel(BaseModel):
    claim: str
    original_text: str
    labels: dict[LabelEnum, str]


def assert_output_json_format(output: dict) -> bool:
    try:
        ClaimModel(**output)
    except ValidationError:
        return False
    return True
```
