### ISSUE TITLE
When adding a new video, tool should accept full URL or just the video ID

### ISSUE THREAD

**Issue by dcorney** [FullFact/health-misinfo-shared#21]
### Requirements

Users should be able to copy/paste the complete URL of a YouTube video such as:
* https://www.youtube.com/watch?v=tQ6l56-ZkeA

Or just the video id such as:
* tQ6l56-ZkeA

Stretch goal (only if it's not much work) - allow more complex URLs, such as:
* https://youtu.be/tQ6l56-ZkeA?feature=shared&t=43
which is generated by the "share" option from within YouTube.

**Comment by andylolz** [comment]
Reopening because this isn’t complete. I think there’s still a frontend change to be made.
