### ISSUE TITLE
Identify caveats in videos

### ISSUE THREAD

**Issue by dcorney** [FullFact/health-misinfo-shared#25]
### Overview

If someone makes an outrageous claim, but in the context of saying things like "But ask your doctor first" or "I'm not a doctor" or "this worked for me but YMMV" etc. then the fact checker should be told of the context as well as the claim, as this might effect their decision to scope the claim further.

This could be an extra variable extracted by our main prompt (i.e. alongside clarity, evidence, type of claim etc.). We can probably find quite a few examples to annotate.

### Requirements

- [x] create a list of widely used caveat phrases, including examples of their use in YouTube videos
- [x] update the training data with this new feature 
- [x] experiment with in-context learning to see if this pulls back caveats while still pulling back the misinformation claims
- [ ] consider if we can distinguish caveat claims from other claims in the UI, e.g. showing the caveat at the top of a videos list of claims

**Comment by c-j-johnston** [comment]
Parking this for now as unsuccessful, without closing. I have [written up findings](https://docs.google.com/document/d/16o1EfobrnSAOw2RY8ZpoAIPT0OAn6nTFdz67CE19gOg/edit). It would be good to come back to this fresh soon.
