### ISSUE TITLE
Changes to copy 

### ISSUE THREAD

**Issue by scoltman** [FullFact/health-misinfo-shared#26]

**Comment by KateOmega** [comment]
Old: Find health misinformation claims in YouTube videos.
New: Find health misinformation in YouTube videos

Old: Please enter a youtube url...
New: Enter a YouTube URL

Old: Get Claims 
New: Analyse 

Old: Previous Searches
New: History

**Comment by andylolz** [comment]
Reopening this – let’s close it once it’s deployed.

**Comment by andylolz** [comment]
Closing because this is deployed now.
