### ISSUE TITLE
CORS requests should succeed

### ISSUE THREAD

**Issue by dcorney** [FullFact/health-misinfo-shared#34]
### Describe the bug

When I type in a video ID and click "get claims" there's no response. The browser tools suggest a CORS error.

### To Reproduce

Steps to reproduce the behaviour:

1. Run the project locally using `docker compose up -d`
2. Browse to http://127.0.0.1:4000/ and log in
3. Enter a video id (e.g. 4WAFHXdTMbY)
4. nothing happens
5. open browser’s dev tools and observe error: 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://127.0.0.1:4000/api/transcripts/4WAFHXdTMbY. (Reason: CORS request did not succeed). Status code: (null).
2
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. 
```

### Expected behaviour

The video should be processed and the claims listed.

**Comment by andylolz** [comment]
> ```
> […] the remote resource at https:// […]
> ```

^^ I think this might be the problem? I think this should be http://

**Comment by andylolz** [comment]
This seems resolved now, but I’ll leave it with @dcorney to confirm and close.

**Comment by andylolz** [comment]
Closing this as resolved 🎉
