### ISSUE TITLE
Investigate genAI evaluation tools

### ISSUE THREAD

**Issue by dcorney** [FullFact/health-misinfo-shared#38]
### Overview

There are a number of tools out there that are designed to speed up prompt engineering, by allowing rapid evaluation or comparison of genAI models. We should investigate these to see if they could be useful.

### Requirements

- [x] Investigate [PromptFoo](https://github.com/promptfoo/promptfoo)
- [x] Investigate [Auto side-by-side](https://cloud.google.com/vertex-ai/generative-ai/docs/models/side-by-side-eval)
- [x] Write/share a short report about what they do, how we could use them, practical considerations, strengths/weaknesses etc.

**Comment by dearden** [comment]
Here's a [write up of my work looking at promptfoo and autosxs](https://docs.google.com/document/d/1D1Tf4bQTM0L1zyQU84HZFocRgKAJ9xJ3bSbQaWSGdV4/edit#heading=h.30spi82oifrb)
