### ISSUE TITLE
Show raw transcript beside paraphrased claims

### ISSUE THREAD

**Issue by dcorney** [FullFact/health-misinfo-shared#42]
### Overview

For clarity, the tool shows paraphrased version of extracted claims. The first thing any fact checker would want to do is to read the actual claim made in context. (This is partly to check the model hasn't hallucinated any extra meaning into the claim.) 

### Requirements

After a video has been processed and a list of claims is displayed, also display the entire transcript in a scrollable area to one side. 

When a claim is clicked, the video should start playing from that point (as per [issue 20](https://github.com/FullFact/health-misinfo-shared/issues/20)) AND also the transcript display should jump to that point in the transcript and highlight the raw text of the claim.

In this mockup, the user has clicked on a claim on the left and can see the raw transcript on the right with the same claim highlighted. (The video should be playing somewhere too.)
![raphael_transcript_linking](https://github.com/FullFact/health-misinfo-shared/assets/2744208/2a93accb-fa18-48f5-bc4a-ad023961c698)

### Notes and additional information

I am not a UI expert! It may be that starting a video AND jumping the text at the same time is confusing or obscure. An alternative might be to add a little "jump to transcript" button beside each extacted claim, maybe with a second button saying "jump to video".

**Comment by andylolz** [comment]
Adding a backend label here too, because we would need to store this raw transcript in the database.
