### ISSUE TITLE
gitignore database.db, and remove it from source code

### ISSUE THREAD

**Issue by andylolz** [FullFact/health-misinfo-shared#44]
database.db is in version control, presumably added in error. It should be removed and gitignored.

**Comment by dcorney** [comment]
Not sure about this one: it might be useful to have a sample of extracted claims/processed videos here rather than starting from scratch. Plus we can store training data in here. Ideally, we'd have scripts to export/import/merge different samples but that's not needed for the MVP.

**Comment by dcorney** [comment]
I like the seed script idea. I'll create a new issue for it so this can stay closed.
