### ISSUE TITLE
Handle multiple analyses of the same video

### ISSUE THREAD

**Issue by dcorney** [FullFact/health-misinfo-shared#62]
### Describe the bug

Currently, if someone enters the video id and clicks analyse for a video that has already been analysed, the model will extract the same (or similar) claims again and add them to the list. 

Instead, we should list the video twice (or more times) on the main page, each linking to its associated set of claims.

This is especially important as we update the prompts/models etc. and may want to compare the same video before and after a change.

### To Reproduce

Steps to reproduce the behaviour:

1. Go to raphael
2. enter a video id and click analyse
3. review the extracted claims
4. enter THE SAME video id and click analyse
5. observe more claims have appeared in the list, roughly doubling it in size

### Expected behaviour

If the same id occurs twice in the list of analysed videos, distinguish by a version number. E.g. 

* 4WAFHXdTMbY
* 4WAFHXdTMbY (v2)
* 4WAFHXdTMbY (v3)

etc.

### Additional context

For reference: in Live, if the same YouTube video is analysed twice, two versions are shown. This is what we want here.

**Comment by andylolz** [comment]
Rather than just v1, v2, v3, is it useful to keep track of some extra metadata, e.g.:
 * the timestamp of when the video analysed;
 * some sort of reference for the prompt that was used;
 * the git SHA?

**Comment by andylolz** [comment]
The issue here is that we’re keying based on the YouTube ID, rather than our own ID. There would need to be some schema changes in order to store different runs of the same video separately.

**Comment by andylolz** [comment]
The issue here is that we’re keying based on the YouTube ID, rather than our own ID. There would need to be some schema changes in order to store different runs of the same video separately.

The schema currently looks like this:

```mermaid
erDiagram
  video_transcripts ||--o{ training_claims : claims
  video_transcripts ||--o{ inferred_claims : claims
  video_transcripts {
    text id PK
    text url
    text metadata
    text transcript
    text status
  }

  training_claims {
    int id PK
    text video_id FK
    text claim
    text label
    integer offset_ms
  }

  inferred_claims {
    int id PK
    text video_id FK
    text claim
    text label
    text model
    integer offset_ms
  }
```

We’d need to move the current video_transcripts id to another field (e.g. youtube_id), add a new auto-increment ID to video_transcripts, and then point at that from the other tables.

**Comment by dcorney** [comment]
For an updated schema, refer to [#71 ](https://github.com/FullFact/health-misinfo-shared/issues/71)
